using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SourceGenerator;

internal class SourceCodeBuilder(){

    internal string Build(
        IList<string> output,
        IMethodSymbol mainMethod)
    {
        string source = $@"// <auto-generated/>
// {DateTime.Now:O}
using System;

namespace {mainMethod.ContainingNamespace.ToDisplayString()}
{{
    public static partial class {mainMethod.ContainingType.Name}
    {{
        static partial void HelloFrom(string name) =>
            Console.WriteLine($""Generator says: Hi from '{{name}}!!!'"");
    }}
}}
";
        return source;
    }

    internal string Build(
        string nameSpace,
        IList<string> output)
    {
        ClassDeclarationSyntax CreateClass(string name) =>
            SyntaxFactory.ClassDeclaration(SyntaxFactory.Identifier(name))
                .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword));

        var ns = SyntaxFactory.NamespaceDeclaration(SyntaxFactory.ParseName(nameSpace)).AddMembers();

        string source = $@"// <auto-generated/>
// {DateTime.Now:O}

// classes:
// {output.StringJoinNL()}

{ns.NormalizeWhitespace()}
";
        return source;
    }
}